name: Docker

on:
  push:
    branches:
      - main
      - test
env:
  SERVICE_NAME: sneaky-forecast-job-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
  deploy:

    name: Deploy to cloudrun
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: sneaky-forecast-job-test
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
    steps:
      - name: Set env to production
        if: endsWith(github.ref, '/main')
        run: |
          echo "SERVICE_NAME=sneaky-forecast-job-prod" >> $GITHUB_ENV
      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: ${{env.IMAGE_NAME}}
          fail-build: false

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy Docker image
        run: gcloud run deploy ${{ env.SERVICE_NAME }} --image $IMAGE_NAME --region europe-west2 --platform managed